#region License
// Moonpie
// 
// Copyright (c) 2022 Stay
// 
// MIT License
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
#endregion

namespace Moonpie.Protocol.Protocol;

public static class PacketTypes
{
    public enum C2S
    {
        HandshakingHandshake,
        StatusPing,
        StatusRequest,
        LoginLoginStart,
        LoginEncryptionResponse,
        LoginPluginResponse,
        PlayTeleportConfirm,
        PlayQueryBlockNBT,
        PlaySetDifficulty,
        PlayChatMessage,
        PlayClientAction,
        PlayClientSettings,
        PlayAutoCompletions,
        PlayContainerActionStatus,
        PlayContainerClickButton,
        PlayContainerSlotClick,
        PlayContainerClose,
        PlayPluginMessage,
        PlayEditBook,
        PlayEntityNBTRequest,
        PlayInteractEntity,
        PlayHeartbeat,
        PlayLockDifficulty,
        PlayPosition,
        PlayPositionAndRotation,
        PlayRotation,
        PlayVehicleMove,
        PlayBoatSteer,
        PlayPickItem,
        PlayCraftingRecipeRequest,
        PlayFlyToggle,
        PlayPlayerAction,
        PlayEntityAction,
        PlayVehicleSteer,
        PlayRecipeBookState,
        PlayAnvilNameSet,
        PlayResourcePackStatus,
        PlayAdvancementTab,
        PlayTradeSelect,
        PlayBeaconEffectSet,
        PlayHotbarSlotSet,
        PlayUpdateCommandBlock,
        PlayItemStackCreate,
        PlayUpdateJigsawBlock,
        PlayUpdateStructureBlock,
        PlaySignTextSet,
        PlayArmSwing,
        PlayEntitySpectate,
        PlayBlockInteract,
        PlayItemUse,
        PlayMinecartCommandBlockSet,
        PlayGenerateStructure,
        PlayDisplayedRecipeSet,
        PlayPlayerGroundChange,
        PlayPrepareCraftingGrid,
        PlayQueryEntityNBT,
        PlayPong
    }

    public enum S2C
    {
        StatusResponse,
        StatusPong,
        LoginKick,
        LoginEncryptionRequest,
        LoginLoginSuccess,
        LoginCompressionSet,
        LoginPluginRequest,
        PlayMobSpawn,
        PlayExperienceOrbSpawn,
        PlayGlobalEntitySpawn,
        PlayPaintingSpawn,
        PlayPlayerEntitySpawn,
        PlayEntityAnimation,
        PlayStatsResponse,
        PlayBlockBreakAck,
        PlayBlockBreakAnimation,
        PlayBlockEntityMetaData,
        PlayBlockAction,
        PlayBlockSet,
        PlayBossBar,
        PlayServerDifficulty,
        PlayChatMessage,
        PlayMassBlockSet,
        PlayAutoCompletions,
        PlayDeclareCommands,
        PlayContainerActionStatus,
        PlayContainerClose,
        PlayContainerItemsSet,
        PlayContainerPropertySet,
        PlayContainerItemSet,
        PlayItemCooldownSet,
        PlayPluginMessage,
        PlayNamedSoundEvent,
        PlayKick,
        PlayEntityStatus,
        PlayExplosion,
        PlayChunkUnload,
        PlayGameEvent,
        PlayHorseContainerOpen,
        PlayHeartbeat,
        PlayChunkData,
        PlayWorldEvent,
        PlayParticle,
        PlayChunkLightData,
        PlayJoinGame,
        PlayMapData,
        PlayVillagerTrades,
        PlayEntityMoveAndRotate,
        PlayEntityRotation,
        PlayEntityRelativeMove,
        PlayVehicleMove,
        PlayBookOpen,
        PlayContainerOpen,
        PlaySignEditorOpen,
        PlayCraftingRecipeResponse,
        PlayPlayerAbilities,
        PlayCombatEvent,
        PlayCombatEventEnd,
        PlayCombatEventEnter,
        PlayCombatEventKill,
        PlayTabListData,
        PlayPlayerFace,
        PlayPositionAndRotation,
        PlayUnlockRecipes,
        PlayEntityDestroy,
        PlayEntityStatusEffectRemove,
        PlayResourcePackRequest,
        PlayRespawn,
        PlayEntityHeadRotation,
        PlaySelectAdvancementTab,
        PlayWorldBorder,
        PlayWorldBorderInitialize,
        PlayCenterSetWorldBorder,
        PlayWorldBorderLerpSize,
        PlayWorldBorderSize,
        PlayWorldBorderSetWarnTime,
        PlayWorldBorderSetWarnBlocks,
        PlayCamera,
        PlayHotbarSlotSet,
        PlayChunkCenterSet,
        PlayObjectivePositionSet,
        PlayEntityMetadata,
        PlayEntityAttach,
        PlayEntityVelocity,
        PlayEntityEquipment,
        PlayExperienceSet,
        PlayHealthSet,
        PlayScoreboardObjective,
        PlayEntityPassengerSet,
        PlayTeams,
        PlayUpdateScore,
        PlayCompassPositionSet,
        PlayWorldTimeSet,
        PlayEntitySoundEvent,
        PlaySoundEvent,
        PlayStopSound,
        PlayTabListTextSet,
        PlayNBTQueryResponse,
        PlayEntityCollectAnimation,
        PlayEntityTeleport,
        PlayAdvancements,
        PlayEntityEffectAttributes,
        PlayEntityStatusEffect,
        PlayDeclareRecipes,
        PlayTags,
        PlayBedUse,
        PlayViewDistanceSet,
        PlayMassChunkData,
        PlaySignTextSet,
        PlayStatistics,
        PlayEntityObjectSpawn,
        PlayTitle,
        PlayTitleClear,
        PlayHotbarTextSet,
        PlayTitleSubtitleSet,
        PlayTitleSet,
        PlayTitleTimesSet,
        PlayEmptyEntityMove,
        PlayCompressionSet,
        PlayAdvancementProgress,
        PlayVibrationSignal,
        PlayPing,
        PlaySimulationDistance,
    }
}